input {
  # Spring Boot에서 TCP로 수신
  tcp {
    port => 5044
    codec => json_lines  # JSON 형태로 수신
  }
}

#filter {
#  # 로그 레벨별 태그 추가
#  if [level] == "ERROR" {
#    mutate { add_tag => ["error"] }
#  }
#
#  # 날짜 파싱
#  date {
#    match => ["@timestamp", "ISO8601"]
#    target => "@timestamp"
#  }
#
#  # 불필요한 필드 제거
#  mutate {
#    remove_field => ["host", "port"]
#  }
#}

output {
  # Elasticsearch로 전송
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "bkrc-logs-%{+YYYY.MM.dd}"  # 날짜별 인덱스
  }
}